export const Country = [
  { text: "United States" },
  { text: "Canada" },
  { text: "Great Britain" },
  { text: "France" },
  { text: "Spain" },
  { text: "Nepal" },
  { text: "Japan" },
  { text: "China" },
  { text: "Taiwan" },
  { text: "Russia" },
  { text: "Philipines" },
  { text: "Ausrtalia" },
  { text: "Fiji" },
  { text: "Thailand" },
  { text: "India" },
  { text: "Pakistan" },
  { text: "Turkey" },
  { text: "Greece" },
  { text: "New Zealand" },
  { text: "Saudi Arabia" },
  { text: "Germany" },
];
