import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header1 from "./components/layout/header1";
import { ProdProvider } from "@/redux/provider/provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ProdProvider><Header1/>{children}</ProdProvider>
      </body>
    </html>
  );
}
